# Defines stages which are to be executed
stages:  
  - build

variables:
  TIBACKUPLIB_DEV_RELEASE: "0.6.1-9"

.build_template: &build_template_def
  before_script:
    - export CI_T_DATE=`LANG=C date -R`
    - touch ./debian/changelog
    - echo ""                                                                             > ./debian/changelog
    - echo "tibackupui (99.9.${CI_PIPELINE_ID}-1) precise; urgency=low"                  >> ./debian/changelog
    - echo ""                                                                            >> ./debian/changelog
    - echo "  * Dev build from master"                                                   >> ./debian/changelog
    - echo ""                                                                            >> ./debian/changelog
    - echo " -- Rene Hadler <rene@hadler.me>  ${CI_T_DATE}"                              >> ./debian/changelog

# Stage "ubuntu"
build-ubuntu-2004-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_dev build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-2004-64

  only:
    - master
  
# Stage "ubuntu"
build-ubuntu-1804-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_dev build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1804-64

  only:
    - master

# Stage "debian"
build-debian-10-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_dev build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-10-64

  only:
    - master

# Stage "debian"
build-debian-9-64-dev:  
  <<: *build_template_def
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_dev build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-9-64

  only:
    - master

# Stage "ubuntu"
build-ubuntu-2004-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib=$TIBACKUPLIB_DEV_RELEASE tibackuplib-dev=$TIBACKUPLIB_DEV_RELEASE -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_release build/tibackup*.deb || true
    - sudo apt purge tibackuplib tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-2004-64

  only:
    - tags

# Stage "ubuntu"
build-ubuntu-1804-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib=$TIBACKUPLIB_DEV_RELEASE tibackuplib-dev=$TIBACKUPLIB_DEV_RELEASE -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_release build/tibackup*.deb || true
    - sudo apt purge tibackuplib tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1804-64

  only:
    - tags

# Stage "debian"
build-debian-9-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib=$TIBACKUPLIB_DEV_RELEASE tibackuplib-dev=$TIBACKUPLIB_DEV_RELEASE -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_release build/tibackup*.deb || true
    - sudo apt purge tibackuplib tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-9-64

  only:
    - tags

# Stage "debian"
build-debian-10-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib=$TIBACKUPLIB_DEV_RELEASE tibackuplib-dev=$TIBACKUPLIB_DEV_RELEASE -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackupui_*.deb build/
    - upload_build_release build/tibackup*.deb || true
    - sudo apt purge tibackuplib tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-10-64

  only:
    - tags
